version: 2.1

jobs:
  build:
    machine: true
    steps:
      - checkout

      # Build the image
      - run: docker build -t crawler ./Crawler

      # Run the image
      - run: docker run --rm crawler --project ./Crawler
